# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

#Cliente.create(rut: '', nombre: '', apellido: '', correo_institucional: '')

Cliente.create(rut: '', nombre: 'Alberto', apellido: 'Pradines Macias', correo_institucional: 'apradines@uss.cl')
Cliente.create(rut: '', nombre: 'Aldo Antonio Altamirano', apellido: 'Navarrete', correo_institucional: 'aldo.altamirano@uss.cl')
Cliente.create(rut: '', nombre: 'Alejandra Contreras', apellido: 'Escanilla', correo_institucional: 'alejandra.contrerase@uss.cl')
Cliente.create(rut: '', nombre: 'Alejandro Javier', apellido: 'Wagner Seguel', correo_institucional: 'alejandro.wagner@uss.cl')
Cliente.create(rut: '', nombre: 'Alexis German', apellido: 'Nuñez Norambuena', correo_institucional: 'alexis.nunez@uss.cl')
Cliente.create(rut: '', nombre: 'Alfonso Felipe', apellido: 'Abad Colil', correo_institucional: 'alfonso.abad@uss.cl')
Cliente.create(rut: '', nombre: 'Alvaro', apellido: 'Barrientos Garnao', correo_institucional: 'abarrientos@uss.cl')
Cliente.create(rut: '', nombre: 'Amparo', apellido: 'Izquierdo Konig', correo_institucional: 'amparo.izquierdo@uss.cl')
Cliente.create(rut: '', nombre: 'Ana Angelica', apellido: 'Cayul Riffo', correo_institucional: 'ana.cayul@uss.cl')
Cliente.create(rut: '', nombre: 'Ana Karina', apellido: 'Burgos Ibañez', correo_institucional: 'ana.burgos@uss.cl')
Cliente.create(rut: '', nombre: 'Ana Maria', apellido: 'Palomino Mendez', correo_institucional: 'anamaria.palomino@uss.cl')
Cliente.create(rut: '', nombre: 'Andrea Cristina', apellido: 'Bustos Salgado', correo_institucional: 'andrea.bustos@uss.cl')
Cliente.create(rut: '', nombre: 'Angel Alejandro', apellido: 'Astroza Constanzo', correo_institucional: 'angel.astroza@uss.cl')
Cliente.create(rut: '', nombre: 'Angelo', apellido: 'Romano', correo_institucional: 'angelo.romano@uss.cl')
Cliente.create(rut: '', nombre: 'Anghela Cristina', apellido: 'Gonzalez Hidalgo', correo_institucional: 'anghela.gonzalez@uss.cl')
Cliente.create(rut: '', nombre: 'Antonio', apellido: 'Garrido', correo_institucional: 'agarrido@uss.cl')
Cliente.create(rut: '', nombre: 'Bernardo Andres', apellido: 'Castillo Pino', correo_institucional: 'bernardo.castillo@uss.cl')
Cliente.create(rut: '', nombre: 'Camila Francisca', apellido: 'Aguayo Muñoz', correo_institucional: 'camila.aguayo@uss.cl')
Cliente.create(rut: '', nombre: 'Camila', apellido: 'Soto Neira', correo_institucional: 'camila.soto@uss.cl')
Cliente.create(rut: '', nombre: 'Carlos Alberto', apellido: 'Aguayo Varela', correo_institucional: 'carlos.aguayo@uss.cl')
Cliente.create(rut: '', nombre: 'Carlos Andres', apellido: 'Ross Rojas', correo_institucional: 'carlos.ross@uss.cl')
Cliente.create(rut: '', nombre: 'Carol Denisse', apellido: 'Troncoso Ruiz', correo_institucional: 'carol.troncoso@uss.cl')
Cliente.create(rut: '', nombre: 'Carol', apellido: 'Hewstone Garcia', correo_institucional: '')
Cliente.create(rut: '', nombre: 'Carol', apellido: 'Saldias Solis', correo_institucional: 'carol.aldiassolis@uss.cl')
Cliente.create(rut: '', nombre: 'Carolina Adriela', apellido: 'Oyarzun Alarcon', correo_institucional: '')
Cliente.create(rut: '', nombre: 'Carolina Andrea', apellido: 'Barriga Islas', correo_institucional: 'carolina.barriga@uss.cl')
Cliente.create(rut: '', nombre: 'Carolina Victoria', apellido: 'Concha Muñoz', correo_institucional: 'carolina.concha@uss.cl')
Cliente.create(rut: '', nombre: 'Carolitza', apellido: 'Zumelzu Barros', correo_institucional: '')
Cliente.create(rut: '', nombre: 'Catalina Andrea', apellido: 'Cardenas Islas', correo_institucional:'')
Cliente.create(rut: '', nombre: 'Claudia Angelica', apellido: 'Contreras Maldonado', correo_institucional: 'claudiaangelica.contreras@uss.cl')
Cliente.create(rut: '', nombre: 'Claudia', apellido: 'Delgado Sanchez', correo_institucional: 'claudia.delgado@uss.cl')
Cliente.create(rut: '', nombre: 'Claudia Jessica', apellido: 'Gonzalez Castro', correo_institucional: 'claudia.gonzalez@uss.cl')
Cliente.create(rut: '', nombre: 'Claudio Andres', apellido: 'Estobar Hansen', correo_institucional: 'claudio.estobar@uss.cl')
Cliente.create(rut: '', nombre: 'Claudio Andres', apellido: 'Sanhueza Tobar', correo_institucional: 'claudio.sanhueza@uss.cl')
Cliente.create(rut: '', nombre: 'Claudio', apellido: 'Suazo Pina', correo_institucional: 'csuazo@uss.cl')
Cliente.create(rut: '', nombre: 'Clotilde Lidia', apellido: 'Martinez Navarrete', correo_institucional: 'clmartinez@uss.cl')
Cliente.create(rut: '', nombre: 'Constanza', apellido: 'Caicha Caroca', correo_institucional: 'constanza.caicha@uss.cl')
Cliente.create(rut: '', nombre: 'Constanza', apellido: 'Gottreux Grollmus', correo_institucional: '')
Cliente.create(rut: '', nombre: 'Consuelo de los Angeles', apellido: 'Vielma Sepulveda', correo_institucional: '')
Cliente.create(rut: '', nombre: 'Cristhoper', apellido: 'Aguilar Ulloa', correo_institucional: 'cristopher.aguilar@uss.cl')
Cliente.create(rut: '', nombre: 'Cristian Rodrigo', apellido: 'Jaramillo Delgado', correo_institucional: '')
Cliente.create(rut: '', nombre: 'Cristobal', apellido: 'Errazuriz Almarza', correo_institucional: 'cristobal.errazuriz@uss.cl')
Cliente.create(rut: '', nombre: 'Daniela', apellido: 'Escudero Escudero', correo_institucional: 'daniela.escudero@uss.cl')
Cliente.create(rut: '', nombre: 'Daniela Paz', apellido: 'Miranda Cruz', correo_institucional: 'daniela.miranda@uss.cl')
Cliente.create(rut: '', nombre: 'Daniela Paz', apellido: 'Sotomayor Aedo', correo_institucional: '')
Cliente.create(rut: '', nombre: 'Deborah', apellido: 'Jones Valle', correo_institucional: 'djones@uss.cl')
Cliente.create(rut: '', nombre: 'Denisse Constanza', apellido: 'Garcia Rudloff', correo_institucional: 'dgarcia@uss.cl')
Cliente.create(rut: '', nombre: 'Denisse Pilar', apellido: 'Benites Caro', correo_institucional: '')
Cliente.create(rut: '', nombre: 'Diego Felipe', apellido: 'Escalona Agurto', correo_institucional:'')
Cliente.create(rut: '', nombre: 'Edison Andres', apellido: 'Pacheco Carroza', correo_institucional:'')
Cliente.create(rut: '', nombre: 'Edison Pacian', apellido: 'Pacheco Saez', correo_institucional: 'edison.pacheco@uss.cl')
Cliente.create(rut: '', nombre: 'Eduardo', apellido: 'Fagalde Ampuero', correo_institucional: 'eduardo.fagalde@uss.cl')
Cliente.create(rut: '', nombre: 'Eduardo', apellido: 'Heilenkotter Anselmo', correo_institucional: 'eduardo.heilenkotter@uss.cl')
Cliente.create(rut: '', nombre: 'Elba Cecilia', apellido: 'Padilla Garcia', correo_institucional: 'elba.padilla@uss.cl')
Cliente.create(rut: '', nombre: 'Emanuel Edgardo', apellido: 'Sepulveda Alvarez', correo_institucional:'')
Cliente.create(rut: '', nombre: 'Erik', apellido: 'Molina Flores', correo_institucional: 'erik.molina@uss.cl')
Cliente.create(rut: '', nombre: 'Evelyn Carolina', apellido: 'Reyes Donoso', correo_institucional: 'evelyn.reyes@uss.cl')
Cliente.create(rut: '', nombre: 'Evelyn Damaris', apellido: 'Oliva Gutierrez', correo_institucional: 'evelyn.oliva@uss.cl')
Cliente.create(rut: '', nombre: 'Evelyn Del Carmen', apellido: 'Lobos Perez', correo_institucional: '')
Cliente.create(rut: '', nombre: 'Felipe Andres', apellido: 'Bustos Zamora', correo_institucional: '')
Cliente.create(rut: '', nombre: 'Felipe Andres', apellido: 'Poblete Valderrama', correo_institucional: 'fernanda.salvo@uss.cl')
Cliente.create(rut: '', nombre: 'Fernando Ignacio', apellido: 'Müller Muñoz', correo_institucional: 'fernando.muller@uss.cl')
Cliente.create(rut: '', nombre: 'Francisca', apellido: 'Garrido Veliz', correo_institucional: '')
Cliente.create(rut: '', nombre: 'Francisco De Dios', apellido: 'Valderas Gfell', correo_institucional: '')
Cliente.create(rut: '', nombre: 'Francisco Enrique', apellido: 'Cea Ananías', correo_institucional: '')
Cliente.create(rut: '', nombre: 'Francisco Javier', apellido: 'Duhalde Clavería', correo_institucional: 'francisco.duhalde@uss.cl')
Cliente.create(rut: '', nombre: 'Francisco Javier', apellido: 'Mena Bastidas', correo_institucional: 'fmena@uss.cl')
Cliente.create(rut: '', nombre: 'Francisco', apellido: 'Videla Caceres', correo_institucional: 'francisco.videla@uss.cl')
Cliente.create(rut: '', nombre: 'Gerald James', apellido: 'Steger Gonzalez', correo_institucional: 'gerald.steger@uss.cl')
Cliente.create(rut: '', nombre: 'Gina Alondra', apellido: 'Osorio Carvajal', correo_institucional: 'gina.osorio@uss.cl')
Cliente.create(rut: '', nombre: 'Giovanna Natalie', apellido: 'Iubini Vidal', correo_institucional: 'giovanna.iubini@uss.cl')
Cliente.create(rut: '', nombre: 'Gizel Cecilia', apellido: 'Rosas Mayorga', correo_institucional: '')
Cliente.create(rut: '', nombre: 'Guido', apellido: 'Rozas Diaz', correo_institucional: '')
Cliente.create(rut: '', nombre: 'Helga Beate Erna', apellido: 'Messing Grube', correo_institucional: 'hmessing@uss.cl')
Cliente.create(rut: '', nombre: 'Heraldo Adolfo', apellido: 'Fuentealba Gonzalez', correo_institucional: 'hfuentealba@uss.cl')
Cliente.create(rut: '', nombre: 'Hernan Andres', apellido: 'Provoste Venegas', correo_institucional: 'hernan.provoste@uss.cl')
Cliente.create(rut: '', nombre: 'Ingrid Anmarie', apellido: 'Beyer Neumann', correo_institucional: 'ingrid.beyer@uss.cl')
Cliente.create(rut: '', nombre: 'Irene', apellido: 'Zimmermann Konekamp', correo_institucional: 'irene.zimmermann@uss.cl')
Cliente.create(rut: '', nombre: 'Isabel', apellido: 'Perez', correo_institucional: 'isabel.perez@uss.cl')
Cliente.create(rut: '', nombre: 'Issis Tamara', apellido: 'Riquelme Rivas', correo_institucional:'')
Cliente.create(rut: '', nombre: 'Ivan Emilio', apellido: 'Gallardo Mutizabal', correo_institucional: 'ivan.gallardo@uss.cl')
Cliente.create(rut: '', nombre: 'Jacqueline', apellido: 'Teylorl', correo_institucional: 'jacqueline.teylorl@uss.cl')
Cliente.create(rut: '', nombre: 'Javier Alejandro', apellido: 'Soto Cardenas', correo_institucional: 'javier.soto@uss.cl')
Cliente.create(rut: '', nombre: 'Javier Ernesto', apellido: 'Bravo Bravo', correo_institucional: '')
Cliente.create(rut: '', nombre: 'Javiera Ignacia', apellido: 'Etcheverry Calderon', correo_institucional: 'javiera.etcheverry@uss.cl')
Cliente.create(rut: '', nombre: 'Jeannette Odisea', apellido: 'Lavalle Caro', correo_institucional:'')
Cliente.create(rut: '', nombre: 'Joaquín', apellido:  'Farías Becerra', correo_institucional: '')
Cliente.create(rut: '', nombre: 'Johanna Escarlet', apellido: 'Zambrano Otarola', correo_institucional: 'johanna.zambrano@uss.cl')
Cliente.create(rut: '', nombre: 'Jonathan', apellido: 'Duarte Reyes', correo_institucional: 'jonathan.duarte@uss.cl')
Cliente.create(rut: '', nombre: 'Jonathan Esteban', apellido: 'Castillo Navarrete', correo_institucional:'')
Cliente.create(rut: '', nombre: 'Jorge Eduardo', apellido: 'Wevar Negrier', correo_institucional: 'jorge.wevar@uss.cl')
Cliente.create(rut: '', nombre: 'José', apellido: 'San Martín'' González', correo_institucional: 'jose.sanmartin@uss.cl')
Cliente.create(rut: '', nombre: 'Juan Andrés', apellido: 'Yavar Fasani', correo_institucional: 'juan.yavar@uss.cl')
Cliente.create(rut: '', nombre: 'Juan Carlos', apellido: 'Acuña Morales', correo_institucional: 'jacuna@uss.cl')
Cliente.create(rut: '', nombre: 'Julio Mauricio', apellido: 'Muñoz Villa', correo_institucional: 'julio.munoz@uss.cl')
Cliente.create(rut: '', nombre: 'Karen Paola', apellido: 'Vial Torres', correo_institucional: 'karen.vial@uss.cl')
Cliente.create(rut: '', nombre: 'Lorena', apellido: 'Liewald Dessy', correo_institucional: 'lliewald@uss.cl')
Cliente.create(rut: '', nombre: 'Luis', apellido: 'Araya', correo_institucional: 'luis.araya@uss.cl')
Cliente.create(rut: '', nombre: 'Luis Daniel', apellido: 'Castillo Castillo', correo_institucional:	'luis.castillo@uss.cl')
Cliente.create(rut: '', nombre: 'Luis Emmanuel', apellido: 'Flores Godoy', correo_institucional: '')
Cliente.create(rut: '', nombre: 'Luis Felipe', apellido: 'Parada Gonzalez', correo_institucional: '')
Cliente.create(rut: '', nombre: 'Luis', apellido: 'Ganga', correo_institucional: 'luis.ganga@uss.cl')
Cliente.create(rut: '', nombre: 'Luis German', apellido: 'Lagos Matus', correo_institucional: '')
Cliente.create(rut: '', nombre: 'Luis Henriquez', apellido: 'Alvear', correo_institucional: '')
Cliente.create(rut: '', nombre: 'Luis Humberto', apellido: 'Vidal Soto', correo_institucional: 'luis.vidal@uss.cl')
Cliente.create(rut: '', nombre: 'Luis Osvaldo', apellido: 'Villar Brevis', correo_institucional: '')
Cliente.create(rut: '', nombre: 'Luis Rafael', apellido: 'Gonzalez Barria', correo_institucional: '')
Cliente.create(rut: '', nombre: 'Luis', apellido: 'Ulloa', correo_institucional: 'lulloa@uss.cl')
Cliente.create(rut: '', nombre: 'Luisa Natalia', apellido: 'Poblete Gutierrez', correo_institucional: 'luisa.poblete@uss.cl')
Cliente.create(rut: '', nombre: 'Macarena Alejandra Ines', apellido: 'Lopez Moren', correo_institucional:'')
Cliente.create(rut: '', nombre: 'Macarena Alejandra', apellido: 'Lamas Aicon', correo_institucional: '')
Cliente.create(rut: '', nombre: 'Marcela', apellido: 'Araya', correo_institucional: 'marcela.araya@uss.cl')
Cliente.create(rut: '', nombre: 'Marcelo', apellido: 'Montecinos Ramirez', correo_institucional: 'mmontecinosr@uss.cl')
Cliente.create(rut: '', nombre: 'Marcos', apellido: 'Muñoz Duarte', correo_institucional: 'marco.munoz@uss.cl')
Cliente.create(rut: '', nombre: 'Maria Cristina', apellido: 'Zambrano Alvarado', correo_institucional: 'maria.zambrano@uss.cl')
Cliente.create(rut: '', nombre: 'Maria Elena', apellido: 'Reyes Paredes', correo_institucional: 'maria.reyesp@uss.cl')
Cliente.create(rut: '', nombre: 'Maria Fernanda', apellido: 'Suarez Rabert', correo_institucional: 'mariafernanda.suarez@uss.cl')
Cliente.create(rut: '', nombre: 'Maria Isabel', apellido: 'Muñoz Marambio', correo_institucional: 'mariaisabel.munoz@uss.cl')
Cliente.create(rut: '', nombre: 'Maria Jose Constanza', apellido: 'Alvarez Soto', correo_institucional: 'mariajose.alvarez@uss.cl')
Cliente.create(rut: '', nombre: 'María Loreto', apellido: 'Horn Ziegele', correo_institucional: 'lhorn@uss.cl')
Cliente.create(rut: '', nombre: 'Maria Paz', apellido: 'Carcamo Ortiz', correo_institucional: 'paz.carcamo@uss.cl')
Cliente.create(rut: '', nombre: 'Maria Veronica', apellido: 'Sandoval Carrasco', correo_institucional:'')
Cliente.create(rut: '', nombre: 'Mariela', apellido: 'Castillo Sepulveda', correo_institucional: 'mariela.castillo@uss.cl')
Cliente.create(rut: '', nombre: 'Marion', apellido: 'Guerrero', correo_institucional: '')
Cliente.create(rut: '', nombre: 'Maritza Alejandra', apellido: 'Vera Aros', correo_institucional: 'maritza.vera@uss.cl')
Cliente.create(rut: '', nombre: 'Marta', apellido: 'Rodriguez Mendez', correo_institucional: '')
Cliente.create(rut: '', nombre: 'Massiel Carolina', apellido: 'Barrientos Arteaga', correo_institucional: 'massiel.barrientos@uss.cl')
Cliente.create(rut: '', nombre: 'Mauricio Alejandro', apellido: 'Valenzuela Uribe', correo_institucional: 'mauricio.valenzuela@uss.cl')
Cliente.create(rut: '', nombre: 'Mauricio Esteban', apellido: 'Vidal Derneder', correo_institucional:'')
Cliente.create(rut: '', nombre: 'Mauricio', apellido: 'Etcheverry Cabrera', correo_institucional: '')
Cliente.create(rut: '', nombre: 'Melisa Carola', apellido: 'Guerrero Coronado', correo_institucional: 'melisa.guerrero@uss.cl')
Cliente.create(rut: '', nombre: 'Miguel Angel', apellido: 'Gomez Gomez', correo_institucional: '')
Cliente.create(rut: '', nombre: 'Miriam Gloria', apellido: 'Suazo Romo', correo_institucional: 'miriam.suazo@uss.cl')
Cliente.create(rut: '', nombre: 'Moisés Eduardo', apellido: 'Monsalve Olavarría', correo_institucional: 'moises.monsalve@uss.cl')
Cliente.create(rut: '', nombre: 'Monica Beatriz', apellido: 'Jara Perez', correo_institucional: 'monica.jara@uss.cl')
Cliente.create(rut: '', nombre: 'Natalia Catalina', apellido: 'Valenzuela Flores', correo_institucional: 'nvalenzuela@uss.cl')
Cliente.create(rut: '', nombre: 'Nataly Alexia', apellido: 'Schneider Vivanco', correo_institucional: 'nataly.schneider@uss.cl')
Cliente.create(rut: '', nombre: 'Octavio Eduardo', apellido: 'Puente Osorio', correo_institucional: 'octavio.puente@uss.cl')
Cliente.create(rut: '', nombre: 'Orietta Aileen', apellido: 'Bahamondes Guzman', correo_institucional: 'orietta.bahamondes@uss.cl')
Cliente.create(rut: '', nombre: 'Orza Madis', apellido: 'Leal Coronado', correo_institucional: '')
Cliente.create(rut: '', nombre: 'Pablo Armando', apellido: 'Willcock Rudloff', correo_institucional:'')
Cliente.create(rut: '', nombre: 'Pamela Ivonne', apellido: 'Fehrmann Rosas', correo_institucional: 'pamela.fehrmann@uss.cl')
Cliente.create(rut: '', nombre: 'Pamela Lucrecia Del Carmen', apellido: 'Veillon Tapia', correo_institucional: 'pamela.veillon@uss.cl')
Cliente.create(rut: '', nombre: 'Paola Alejandra', apellido: 'Manosalva Obando', correo_institucional: 'paola.manosalva@uss.cl')
Cliente.create(rut: '', nombre: 'Patricia Lorena', apellido: 'Duarte Seguel', correo_institucional: '')
Cliente.create(rut: '', nombre: 'Patricia', apellido: 'Provoste Roussel', correo_institucional: 'pprovoste@uss.cl')
Cliente.create(rut: '', nombre: 'Patricio Andres', apellido: 'Caamaño Bustos', correo_institucional: 'patricio.caamano@uss.cl')
Cliente.create(rut: '', nombre: 'Patricio Andres', apellido: 'Diaz Milanca', correo_institucional: '')
Cliente.create(rut: '', nombre: 'Patrizia', apellido: 'Macchiavello Ballart', correo_institucional: 'patrizia.macchiavello@uss.cl')
Cliente.create(rut: '', nombre: 'Paula Fernanda', apellido: 'Aguilar Peña', correo_institucional: '')
Cliente.create(rut: '', nombre: 'Paula Leticia', apellido: 'Olivera Paredes', correo_institucional: 'paula.olivera@uss.cl')
Cliente.create(rut: '', nombre: 'Paulette Isabel', apellido: 'Obreque Montecinos', correo_institucional: '')
Cliente.create(rut: '', nombre: 'Paulina Andrea', apellido: 'Salas Alarcon', correo_institucional: 'paulina.salas@uss.cl')
Cliente.create(rut: '', nombre: 'Paulina Loreto', apellido: 'Tapia Vidal', correo_institucional: 'pltapia@uss.cl')
Cliente.create(rut: '', nombre: 'Paulo Cesar', apellido: 'Solis Rosales', correo_institucional: 'paulo.solis@uss.cl')
Cliente.create(rut: '', nombre: 'Ricardo Arnoldo', apellido: 'Klesse Perez de Arce', correo_institucional: 'ricardo.klesse@uss.cl')
Cliente.create(rut: '', nombre: 'Roberto Alejandro', apellido: 'Zuniga Castillo', correo_institucional: '')
Cliente.create(rut: '', nombre: 'Roberto Andres', apellido: 'Buchhorsts Vargas', correo_institucional: 'roberto.buchhorsts@uss.cl')
Cliente.create(rut: '', nombre: 'Roberto Esteban', apellido: 'Pinochet Mejias', correo_institucional: 'roberto.pinochet@uss.cl')
Cliente.create(rut: '', nombre: 'Rocio Fernanda', apellido: 'Negron Orrego', correo_institucional: 'rocio.negron@uss.cl')
Cliente.create(rut: '', nombre: 'Rodrigo', apellido: 'Yobanolo Bonvalet', correo_institucional: '')
Cliente.create(rut: '', nombre: 'Rogers Leonardo', apellido: 'Antecao Soto', correo_institucional: '')
Cliente.create(rut: '', nombre: 'Romina Andrea', apellido: 'Cisterna Marchant', correo_institucional: 'romina.cisterna@uss.cl')
Cliente.create(rut: '', nombre: 'Rommy Elizabeth', apellido: 'Bartholomaus Rodriguez', correo_institucional: 'rommy.bartholomaus@uss.cl')
Cliente.create(rut: '', nombre: 'Rosa Marcela', apellido: 'Fernandez Valderas', correo_institucional: 'marcela.fernandez@uss.cl')
Cliente.create(rut: '', nombre: 'Rosana Fabiola', apellido: 'Alday Cuevas', correo_institucional: 'ralday@uss.cl')
Cliente.create(rut: '', nombre: 'Sandra Norma del Carmen', apellido: 'Fuentes Mardones', correo_institucional:'')
Cliente.create(rut: '', nombre: 'Sandra', apellido: 'Palma Rosas', correo_institucional: 'sandra.palma@uss.cl')
Cliente.create(rut: '', nombre: 'Sergio Gerardo', apellido: 'Borquez Castro', correo_institucional: 'sergio.borquez@uss.cl')
Cliente.create(rut: '', nombre: 'Silvana Rocio De Lourdes', apellido: 'Silva Miranda', correo_institucional: '')
Cliente.create(rut: '', nombre: 'Silvia Elizabeth', apellido: 'Fica Velasquez', correo_institucional: '')
Cliente.create(rut: '', nombre: 'Sofia Eroland', apellido: 'Alvarez Pichun', correo_institucional: '')
Cliente.create(rut: '', nombre: 'Stella Maris', apellido: 'Januario da Silva', correo_institucional: 'stella.januario@uss.cl')
Cliente.create(rut: '', nombre: 'Susana', apellido: 'Wevar Porflit', correo_institucional: 'susana.wevar@uss.cl')
Cliente.create(rut: '', nombre: 'Suzuki Koda', apellido: 'Fuentes', correo_institucional: 'suzuki.koda@uss.cl')
Cliente.create(rut: '', nombre: 'Tamara', apellido: 'Fernandez Puratich', correo_institucional: 'tamara.fernandez@uss.cl')
Cliente.create(rut: '', nombre: 'Teresa Jeanette', apellido: 'Viviana Vidal', correo_institucional: 'teresa.vidal@uss.cl')
Cliente.create(rut: '', nombre: 'Texia Gabriela', apellido: 'Medina Mellado', correo_institucional: 'texia.medina@uss.cl')
Cliente.create(rut: '', nombre: 'Veronica Andrea', apellido: 'Silva Perez', correo_institucional:'')
Cliente.create(rut: '', nombre: 'Victor Alejandro', apellido: 'Parra Maldo', correo_institucional: 'victor.parra@uss.cl')
Cliente.create(rut: '', nombre: 'Victor Hernan', apellido: 'Carrillo Carrillo', correo_institucional: 'victor.carrillo@uss.cl')
Cliente.create(rut: '', nombre: 'Viviana', apellido: 'Coronado Rojas', correo_institucional: '')
Cliente.create(rut: '', nombre: 'Viviana', apellido: 'Matamala', correo_institucional: '')
Cliente.create(rut: '', nombre: 'Yasmin Carola', apellido: 'Assef Riquelme', correo_institucional: 'yasmin.assef@uss.cl')
Cliente.create(rut: '', nombre: 'Yasna Paola', apellido: 'Carrillo Carrillo', correo_institucional: 'yasna.carrillo@uss.cl')
Cliente.create(rut: '', nombre: 'Yuli', apellido: 'Cariaga Cariaga', correo_institucional: '')
Cliente.create(rut: '', nombre: 'Zarella Elsa', apellido: 'Stuardo Cavada', correo_institucional: '')
